# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addnumbers.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='addnumbers.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x61\x64\x64numbers.proto\"\x1d\n\x05\x41\x64\x64In\x12\t\n\x01x\x18\x01 \x01(\x03\x12\t\n\x01y\x18\x02 \x01(\x03\"\x17\n\x06\x41\x64\x64Out\x12\r\n\x05value\x18\x01 \x01(\x03\x32$\n\nAddNumbers\x12\x16\n\x03\x61\x64\x64\x12\x06.AddIn\x1a\x07.AddOutb\x06proto3')
)




_ADDIN = _descriptor.Descriptor(
  name='AddIn',
  full_name='AddIn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='AddIn.x', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='AddIn.y', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=49,
)


_ADDOUT = _descriptor.Descriptor(
  name='AddOut',
  full_name='AddOut',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='AddOut.value', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['AddIn'] = _ADDIN
DESCRIPTOR.message_types_by_name['AddOut'] = _ADDOUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddIn = _reflection.GeneratedProtocolMessageType('AddIn', (_message.Message,), {
  'DESCRIPTOR' : _ADDIN,
  '__module__' : 'addnumbers_pb2'
  # @@protoc_insertion_point(class_scope:AddIn)
  })
_sym_db.RegisterMessage(AddIn)

AddOut = _reflection.GeneratedProtocolMessageType('AddOut', (_message.Message,), {
  'DESCRIPTOR' : _ADDOUT,
  '__module__' : 'addnumbers_pb2'
  # @@protoc_insertion_point(class_scope:AddOut)
  })
_sym_db.RegisterMessage(AddOut)



_ADDNUMBERS = _descriptor.ServiceDescriptor(
  name='AddNumbers',
  full_name='AddNumbers',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=76,
  serialized_end=112,
  methods=[
  _descriptor.MethodDescriptor(
    name='add',
    full_name='AddNumbers.add',
    index=0,
    containing_service=None,
    input_type=_ADDIN,
    output_type=_ADDOUT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADDNUMBERS)

DESCRIPTOR.services_by_name['AddNumbers'] = _ADDNUMBERS

# @@protoc_insertion_point(module_scope)
