# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import DigitClassifier_pb2 as DigitClassifier__pb2


class DigitClassifierStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Classify = channel.unary_unary(
        '/DigitClassifier/Classify',
        request_serializer=DigitClassifier__pb2.Image.SerializeToString,
        response_deserializer=DigitClassifier__pb2.Classification.FromString,
        )


class DigitClassifierServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Classify(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DigitClassifierServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Classify': grpc.unary_unary_rpc_method_handler(
          servicer.Classify,
          request_deserializer=DigitClassifier__pb2.Image.FromString,
          response_serializer=DigitClassifier__pb2.Classification.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'DigitClassifier', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
